services:
  postgres:
    image: postgres:15
    container_name: db-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: nuxt-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run dev"
    platform: linux/arm64

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data

volumes:
  pgdata:
  redis_data:
